### ISSUE TITLE
Cosmetic issue visable when using MQTT.

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [gruijter/com.gruijter.youless#3]
In mqtt (using mqtt hub and client) its possible to send information to mqtt. But in mqtt it seems that there is a translation "error".

![afbeelding](https://user-images.githubusercontent.com/28575285/68975706-45a3d180-07f4-11ea-828c-153094b1f164.png)

**Comment by gruijter** [comment]
Euh, ok. But Im not the author of the mqtt apps. So I have no clue what you posted 😂. Is there something wrong in the youless app? If so what? And by the way: please switch to the 'Enelogic and Youless' app, because the youless app is not being updated anymore.

https://homey.app/a/com.gruijter.enelogic

**Comment by MP-ICT-Diensten** [comment]
Sorry, you are right. And I even think I need to address this to homey, because om v3.00  the topic was sensor/thuis/ls120p1   but in 3.1.0 it is sensor/home/ls120p1.

I do use the enelogic app :)  Because the new Homey store does not have links to github pages anymore I have searched on github and found this first :)
